[package]
name = "bevy_picking_example"
version = "0.1.0"
authors = ["tylerkayser <me@tylerkayser.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4"
bevy_mod_picking = "0.3.1"